from pathlib import Path
p=Path('docs/engineer-osint/ui-v43-entity-detail.js')
s=p.read_text(encoding='utf-8')
old_css=".v43-asset img{max-width:100%;max-height:360px;object-fit:contain;border-radius:9px;background:#071019}.v43-local-photo{margin:12px 0 10px;display:grid;gap:7px}.v43-local-photo img{display:block;width:100%;max-height:430px;object-fit:contain;border-radius:12px;background:#071019}.v43-local-photo figcaption{font-size:.78rem;color:#a9bed0}.v43-local-photo a{color:#9bc7f2}@media(max-width:760px)"
new_css=".v43-asset img{max-width:100%;max-height:360px;object-fit:contain;border-radius:9px;background:#071019}@media(max-width:760px)"
if s.count(old_css)!=1: raise SystemExit('expected one v4602 CSS addition')
s=s.replace(old_css,new_css,1)
old="  function renderLocalPhoto(r){const p=localPhotoFor(r);if(!p)return'';const src=String(p.local_image_path||'').replace(/^\\/+/,''),credit=[p.author_rightsholder,p.license].filter(Boolean).join(' · '),origin=p.origin_url||p.source_acquisition_url||'';return `<figure class=\"v43-local-photo\" data-v43-local-photo=\"${esc(r.id)}\"><img loading=\"eager\" src=\"${esc(src)}\" alt=\"${esc(title(r))}\"><figcaption>${esc(cs('Lokálně archivovaný, licenčně ověřený obrázek','Locally archived, license-verified image'))}${credit?` · ${esc(credit)}`:''}${origin?` · <a href=\"${esc(origin)}\" target=\"_blank\" rel=\"noopener noreferrer\">${esc(cs('zdroj','source'))} ↗</a>`:''}</figcaption></figure>`}"
new="  function renderLocalPhoto(r){const p=localPhotoFor(r);if(!p)return'';const src=String(p.local_image_path||'').replace(/^\\/+/,''),credit=[p.author_rightsholder,p.license].filter(Boolean).join(' · '),origin=p.origin_url||p.source_acquisition_url||'';return `<figure class=\"v43-local-photo\" data-v43-local-photo=\"${esc(r.id)}\" style=\"margin:12px 0 10px;display:grid;gap:7px\"><img loading=\"eager\" src=\"${esc(src)}\" alt=\"${esc(title(r))}\" style=\"display:block;width:100%;max-height:430px;object-fit:contain;border-radius:12px;background:#071019\"><figcaption style=\"font-size:.78rem;color:#a9bed0\">${esc(cs('Lokálně archivovaný, licenčně ověřený obrázek','Locally archived, license-verified image'))}${credit?` · ${esc(credit)}`:''}${origin?` · <a href=\"${esc(origin)}\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color:#9bc7f2\">${esc(cs('zdroj','source'))} ↗</a>`:''}</figcaption></figure>`}"
if s.count(old)!=1: raise SystemExit('expected one renderLocalPhoto implementation')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
